"""esquema inicial

Revision ID: 970626c5b21a
Revises:
Create Date: 2026-08-31 11:52:11.065346
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "970626c5b21a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Native PostgreSQL enum types created implicitly by ``create_table``.
#: Alembic's autogenerate does NOT emit a matching DROP TYPE on downgrade, so a
#: downgrade followed by an upgrade fails with "type already exists". They are
#: dropped explicitly below, which is what makes this migration reversible.
TIPOS_ENUM: tuple[str, ...] = (
    "tipo_documento_enum",
    "regimen_enum",
    "especialidad_enum",
    "estado_slot_enum",
    "estado_cita_enum",
    "concepto_cargo_enum",
    "estado_cargo_enum",
    "prioridad_lista_enum",
    "estado_lista_enum",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clinica",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=160), nullable=False),
        sa.Column("nit", sa.String(length=20), nullable=False),
        sa.Column("especialidad", sa.String(length=80), nullable=False),
        sa.Column("direccion", sa.String(length=200), nullable=True),
        sa.Column("telefono", sa.String(length=30), nullable=True),
        sa.Column("ciudad", sa.String(length=80), nullable=False),
        sa.Column("zona_horaria", sa.String(length=50), nullable=False),
        sa.Column(
            "creada_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "actualizada_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nit"),
    )
    op.create_table(
        "paciente",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "tipo_documento",
            sa.Enum("CC", "TI", "CE", "PA", "RC", "PPT", name="tipo_documento_enum"),
            nullable=False,
        ),
        sa.Column("documento", sa.String(length=20), nullable=False),
        sa.Column("nombre", sa.String(length=160), nullable=False),
        sa.Column("telefono", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(length=160), nullable=True),
        sa.Column("fecha_nacimiento", sa.Date(), nullable=True),
        sa.Column(
            "regimen",
            sa.Enum("contributivo", "subsidiado", "particular", "soat", name="regimen_enum"),
            nullable=False,
        ),
        sa.Column("afiliacion_activa", sa.Boolean(), nullable=False),
        sa.Column("eps", sa.String(length=120), nullable=True),
        sa.Column("nivel_cuota_moderadora", sa.Integer(), nullable=False),
        sa.Column("consentimiento_datos_clinicos", sa.Boolean(), nullable=False),
        sa.Column("consentimiento_otorgado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "creada_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "actualizada_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "nivel_cuota_moderadora between 1 and 3", name="ck_paciente_nivel_cuota"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tipo_documento", "documento", name="uq_paciente_documento"),
    )
    op.create_index(op.f("ix_paciente_documento"), "paciente", ["documento"], unique=False)
    op.create_index(
        "ix_paciente_nombre_lower", "paciente", [sa.literal_column("lower(nombre)")], unique=False
    )
    op.create_index(op.f("ix_paciente_regimen"), "paciente", ["regimen"], unique=False)
    op.create_table(
        "profesional",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("clinica_id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=160), nullable=False),
        sa.Column("registro", sa.String(length=40), nullable=False),
        sa.Column(
            "especialidad",
            sa.Enum(
                "odontologia_general",
                "ortodoncia",
                "endodoncia",
                "periodoncia",
                "odontopediatria",
                name="especialidad_enum",
            ),
            nullable=False,
        ),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column(
            "creada_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "actualizada_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["clinica_id"], ["clinica.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("registro"),
    )
    op.create_index(op.f("ix_profesional_clinica_id"), "profesional", ["clinica_id"], unique=False)
    op.create_index(
        op.f("ix_profesional_especialidad"), "profesional", ["especialidad"], unique=False
    )
    op.create_table(
        "agenda_slot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profesional_id", sa.Integer(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("inicio", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fin", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "estado",
            sa.Enum("libre", "ocupado", "bloqueado", name="estado_slot_enum"),
            nullable=False,
        ),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column(
            "creada_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "actualizada_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("fin > inicio", name="ck_slot_rango_valido"),
        sa.ForeignKeyConstraint(["profesional_id"], ["profesional.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profesional_id", "inicio", name="uq_slot_profesional_inicio"),
    )
    op.create_index(
        "ix_slot_busqueda", "agenda_slot", ["fecha", "estado", "profesional_id"], unique=False
    )
    op.create_table(
        "cita",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("paciente_id", sa.Integer(), nullable=False),
        sa.Column("profesional_id", sa.Integer(), nullable=False),
        sa.Column("slot_id", sa.Integer(), nullable=False),
        sa.Column(
            "estado",
            sa.Enum(
                "agendada",
                "confirmada",
                "en_espera",
                "atendida",
                "cancelada",
                "reprogramada",
                "no_asistio",
                name="estado_cita_enum",
            ),
            nullable=False,
        ),
        sa.Column("motivo", sa.Text(), nullable=True),
        sa.Column("motivo_registrado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("motivo_registrado_por", sa.String(length=120), nullable=True),
        sa.Column("motivo_cancelacion", sa.Text(), nullable=True),
        sa.Column("creada_por", sa.String(length=120), nullable=False),
        sa.Column("idempotency_key", sa.String(length=80), nullable=True),
        sa.Column("cita_origen_id", sa.Integer(), nullable=True),
        sa.Column(
            "creada_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "actualizada_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["cita_origen_id"], ["cita.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["paciente_id"], ["paciente.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["profesional_id"], ["profesional.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["slot_id"], ["agenda_slot.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_cita_idempotency"),
    )
    op.create_index(op.f("ix_cita_estado"), "cita", ["estado"], unique=False)
    op.create_index("ix_cita_paciente_estado", "cita", ["paciente_id", "estado"], unique=False)
    op.create_index(op.f("ix_cita_profesional_id"), "cita", ["profesional_id"], unique=False)
    op.create_index(
        "uq_cita_slot_activa",
        "cita",
        ["slot_id"],
        unique=True,
        postgresql_where=sa.text("estado in ('agendada','confirmada','en_espera','atendida')"),
    )
    op.create_table(
        "lista_espera",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("paciente_id", sa.Integer(), nullable=False),
        sa.Column(
            "especialidad",
            sa.Enum(
                "odontologia_general",
                "ortodoncia",
                "endodoncia",
                "periodoncia",
                "odontopediatria",
                name="especialidad_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "prioridad",
            sa.Enum("urgencia", "antiguedad", name="prioridad_lista_enum"),
            nullable=False,
        ),
        sa.Column(
            "estado",
            sa.Enum("activa", "ofrecida", "aceptada", "retirada", name="estado_lista_enum"),
            nullable=False,
        ),
        sa.Column("notas", sa.String(length=300), nullable=True),
        sa.Column("ofrecida_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("slot_ofrecido_id", sa.Integer(), nullable=True),
        sa.Column(
            "creada_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "actualizada_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["paciente_id"], ["paciente.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["slot_ofrecido_id"], ["agenda_slot.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_lista_espera_cola",
        "lista_espera",
        ["especialidad", "estado", "prioridad", "creada_en"],
        unique=False,
    )
    op.create_index(
        "uq_lista_espera_activa",
        "lista_espera",
        ["paciente_id", "especialidad"],
        unique=True,
        postgresql_where=sa.text("estado = 'activa'"),
    )
    op.create_table(
        "cargo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("paciente_id", sa.Integer(), nullable=False),
        sa.Column("cita_id", sa.Integer(), nullable=True),
        sa.Column(
            "concepto",
            sa.Enum(
                "copago", "cuota_moderadora", "particular", "no_show", name="concepto_cargo_enum"
            ),
            nullable=False,
        ),
        sa.Column("monto", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("descripcion", sa.String(length=200), nullable=True),
        sa.Column(
            "estado",
            sa.Enum("pendiente", "pagado", "anulado", name="estado_cargo_enum"),
            nullable=False,
        ),
        sa.Column("vencimiento", sa.Date(), nullable=False),
        sa.Column("pagado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "creada_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "actualizada_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("monto >= 0", name="ck_cargo_monto_no_negativo"),
        sa.ForeignKeyConstraint(["cita_id"], ["cita.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["paciente_id"], ["paciente.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_cargo_paciente_estado", "cargo", ["paciente_id", "estado"], unique=False)
    op.create_table(
        "cita_historial",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("cita_id", sa.Integer(), nullable=False),
        sa.Column(
            "estado_anterior",
            sa.Enum(
                "agendada",
                "confirmada",
                "en_espera",
                "atendida",
                "cancelada",
                "reprogramada",
                "no_asistio",
                name="estado_cita_enum",
            ),
            nullable=True,
        ),
        sa.Column(
            "estado_nuevo",
            sa.Enum(
                "agendada",
                "confirmada",
                "en_espera",
                "atendida",
                "cancelada",
                "reprogramada",
                "no_asistio",
                name="estado_cita_enum",
            ),
            nullable=False,
        ),
        sa.Column("usuario", sa.String(length=120), nullable=False),
        sa.Column("motivo", sa.Text(), nullable=True),
        sa.Column(
            "momento", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["cita_id"], ["cita.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_historial_cita_momento", "cita_historial", ["cita_id", "momento"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_historial_cita_momento", table_name="cita_historial")
    op.drop_table("cita_historial")
    op.drop_index("ix_cargo_paciente_estado", table_name="cargo")
    op.drop_table("cargo")
    op.drop_index(
        "uq_lista_espera_activa",
        table_name="lista_espera",
        postgresql_where=sa.text("estado = 'activa'"),
    )
    op.drop_index("ix_lista_espera_cola", table_name="lista_espera")
    op.drop_table("lista_espera")
    op.drop_index(
        "uq_cita_slot_activa",
        table_name="cita",
        postgresql_where=sa.text("estado in ('agendada','confirmada','en_espera','atendida')"),
    )
    op.drop_index(op.f("ix_cita_profesional_id"), table_name="cita")
    op.drop_index("ix_cita_paciente_estado", table_name="cita")
    op.drop_index(op.f("ix_cita_estado"), table_name="cita")
    op.drop_table("cita")
    op.drop_index("ix_slot_busqueda", table_name="agenda_slot")
    op.drop_table("agenda_slot")
    op.drop_index(op.f("ix_profesional_especialidad"), table_name="profesional")
    op.drop_index(op.f("ix_profesional_clinica_id"), table_name="profesional")
    op.drop_table("profesional")
    op.drop_index(op.f("ix_paciente_regimen"), table_name="paciente")
    op.drop_index("ix_paciente_nombre_lower", table_name="paciente")
    op.drop_index(op.f("ix_paciente_documento"), table_name="paciente")
    op.drop_table("paciente")
    op.drop_table("clinica")
    # ### end Alembic commands ###

    # Not generated by autogenerate: without this the downgrade leaves orphan
    # types behind and the next upgrade cannot recreate them.
    conexion = op.get_bind()
    for nombre in TIPOS_ENUM:
        sa.Enum(name=nombre).drop(conexion, checkfirst=True)
