"""Finish the English rename: `affiliation`, and the names PostgreSQL chose.

Two loose ends the earlier phases left behind.

`afiliacion_active` stayed Spanish because affiliation looked like a Colombian
term. It is not: `affiliation` carries it faithfully, unlike `cartera`,
`en_mora`, `regimen` or `cuota_moderadora`, which stay Spanish here and
everywhere else. Only the column moves; the values it sits next to
(`contributivo`, `subsidiado`) are untouched.

The second half is cosmetic until it is not. Phase 5 renamed the tables and
columns but left the constraint, index and sequence names PostgreSQL had
generated from the *old* table names, so `patient` still answered to
`paciente_pkey`. Those names surface in errors a person has to read: a
duplicate document raised "violates unique constraint clinica_nit_key" against
a table called `clinic`. Renaming them is catalogue-only, exactly like phase 5:
no row moves, no index is rebuilt, and a sequence keeps its owning column
because the DEFAULT refers to it by identity, not by name.

Revision ID: a3f7c21b5e48
Revises: 8b7d41e0c6a2
"""

from __future__ import annotations

from alembic import op

revision: str = "a3f7c21b5e48"
down_revision: str | None = "8b7d41e0c6a2"
branch_labels: None = None
depends_on: None = None

#: table -> (old column, new column)
COLUMNS: tuple[tuple[str, str, str], ...] = (
    ("patient", "afiliacion_active", "affiliation_active"),
)

#: table -> (old constraint, new constraint). Generated by PostgreSQL from the
#: pre-phase-5 table names, so every one of them still reads in Spanish.
CONSTRAINTS: tuple[tuple[str, str, str], ...] = (
    ("agenda_slot", "agenda_slot_profesional_id_fkey", "agenda_slot_professional_id_fkey"),
    ("appointment", "cita_pkey", "appointment_pkey"),
    ("appointment", "cita_paciente_id_fkey", "appointment_patient_id_fkey"),
    ("appointment", "cita_profesional_id_fkey", "appointment_professional_id_fkey"),
    ("appointment", "cita_slot_id_fkey", "appointment_slot_id_fkey"),
    ("appointment", "cita_cita_origen_id_fkey", "appointment_source_appointment_id_fkey"),
    ("appointment_history", "cita_historial_pkey", "appointment_history_pkey"),
    (
        "appointment_history",
        "cita_historial_cita_id_fkey",
        "appointment_history_appointment_id_fkey",
    ),
    ("charge", "cargo_pkey", "charge_pkey"),
    ("charge", "cargo_paciente_id_fkey", "charge_patient_id_fkey"),
    ("charge", "cargo_cita_id_fkey", "charge_appointment_id_fkey"),
    ("clinic", "clinica_pkey", "clinic_pkey"),
    ("clinic", "clinica_nit_key", "clinic_nit_key"),
    ("patient", "paciente_pkey", "patient_pkey"),
    ("professional", "profesional_pkey", "professional_pkey"),
    ("professional", "profesional_clinica_id_fkey", "professional_clinic_id_fkey"),
    ("professional", "profesional_registro_key", "professional_license_number_key"),
    ("waiting_list", "lista_espera_pkey", "waiting_list_pkey"),
    ("waiting_list", "lista_espera_paciente_id_fkey", "waiting_list_patient_id_fkey"),
    ("waiting_list", "lista_espera_slot_ofrecido_id_fkey", "waiting_list_offered_slot_id_fkey"),
)

#: Enum type names. Following the rule the project already applies to dict keys
#: and class names: the structure is English, the values it holds stay Spanish
#: where they are legal terms. `regimen_enum` keeps its name because `regimen`
#: *is* the domain term, not a generic wrapper around one.
ENUM_TYPES: tuple[tuple[str, str], ...] = (
    ("tipo_documento_enum", "document_type_enum"),
    ("concepto_cargo_enum", "charge_concept_enum"),
)

#: Identity sequences, named after the table that used to own them.
SEQUENCES: tuple[tuple[str, str], ...] = (
    ("cargo_id_seq", "charge_id_seq"),
    ("cita_historial_id_seq", "appointment_history_id_seq"),
    ("cita_id_seq", "appointment_id_seq"),
    ("clinica_id_seq", "clinic_id_seq"),
    ("lista_espera_id_seq", "waiting_list_id_seq"),
    ("paciente_id_seq", "patient_id_seq"),
    ("profesional_id_seq", "professional_id_seq"),
)


def _apply(*, reverse: bool) -> None:
    for table, old, new in COLUMNS:
        a, b = (new, old) if reverse else (old, new)
        op.alter_column(table, a, new_column_name=b)
    for table, old, new in CONSTRAINTS:
        a, b = (new, old) if reverse else (old, new)
        op.execute(f"ALTER TABLE {table} RENAME CONSTRAINT {a} TO {b}")
    for old, new in SEQUENCES:
        a, b = (new, old) if reverse else (old, new)
        op.execute(f"ALTER SEQUENCE {a} RENAME TO {b}")
    for old, new in ENUM_TYPES:
        a, b = (new, old) if reverse else (old, new)
        op.execute(f"ALTER TYPE {a} RENAME TO {b}")


def upgrade() -> None:
    _apply(reverse=False)


def downgrade() -> None:
    _apply(reverse=True)
